
version: "3.7"
services:
  db:
    build: ./migration
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: university
    restart: 'always'
    networks: 
    - backend
    healthcheck:
      test: "exit 0"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks: 
    - backend

networks:
  backend:
    driver: bridge
    name: backend