default:
  app:
    version: 1 
    environment: "local" # local, development, staging, production
    port: 3001
  database: 
    host: localhost
    username: root  
    password: password 
    dbName: "university"

